version: '3.8'
services:
  node1:
    build: .
    environment:
      - NODE_ID=1
      - PEERS=node2,node3
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Mount your code for live reload

  node2:
    build: .
    environment:
      - NODE_ID=2
      - PEERS=node1,node3
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app

  node3:
    build: .
    environment:
      - NODE_ID=3
      - PEERS=node1,node2
    ports:
      - "8002:8000"
    volumes:
      - ./app:/app