version: '3.9'

services:
  db:
    image: postgres:15
    container_name: distlog_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: distributed_logging_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  logger1:
    build: .
    container_name: logger_node1
    environment:
      - SERVER_NAME=logger1
    ports:
      - "8001:8000"
    volumes:
      - .:/app  # ✅ mount code so live reload works
    depends_on:
      - db

  logger2:
    build: .
    container_name: logger_node2
    environment:
      - SERVER_NAME=logger2
    ports:
      - "8002:8000"
    volumes:
      - .:/app  # ✅ mount code so live reload works
    depends_on:
      - db

volumes:
  pgdata:
